# Generated by Django 5.0.7 on 2024-07-26 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_img', models.ImageField(upload_to='static/assets/category_img')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=50)),
                ('category_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryimg')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=50)),
                ('sub_category_img', models.ImageField(upload_to='static/assets/category_img')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShopListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('business_rating', models.IntegerField(default=0)),
                ('business_address', models.CharField(max_length=100)),
                ('business_banner', models.ImageField(upload_to='static/assets/listedShops')),
                ('sub_domain_one', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_two', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_three', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_four', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_five', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_six', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_seven', models.CharField(blank=True, max_length=50, null=True)),
                ('business_origin', models.CharField(default='India', max_length=50)),
                ('business_dob', models.CharField(default='N/A', max_length=50)),
                ('business_gst', models.CharField(default='N/A', max_length=50)),
                ('business_description', models.CharField(max_length=1000)),
                ('business_img_one', models.ImageField(upload_to='static/assets/listedShops')),
                ('business_img_two', models.ImageField(upload_to='static/assets/listedShops')),
                ('business_img_three', models.ImageField(upload_to='static/assets/listedShops')),
                ('business_no', models.CharField(max_length=15)),
                ('business_email', models.CharField(max_length=50)),
                ('insta_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('gmap_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maincategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
            ],
        ),
    ]
