# Generated by Django 5.0.7 on 2024-07-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplisting',
            name='business_banner',
        ),
        migrations.RemoveField(
            model_name='shoplisting',
            name='business_img_one',
        ),
        migrations.RemoveField(
            model_name='shoplisting',
            name='business_img_three',
        ),
        migrations.RemoveField(
            model_name='shoplisting',
            name='business_img_two',
        ),
    ]
