# Generated by Django 5.0.7 on 2024-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_shoplisting_business_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplisting',
            name='business_banner',
            field=models.ImageField(default='', upload_to='static/assets/listedShops'),
            preserve_default=False,
        ),
    ]
