# Generated by Django 5.0.7 on 2024-07-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shoplisting_business_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplisting',
            name='business_img_one',
            field=models.ImageField(default='', upload_to='static/assets/listedShops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='business_img_three',
            field=models.ImageField(default='', upload_to='static/assets/listedShops'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='business_img_two',
            field=models.ImageField(default='', upload_to='static/assets/listedShops'),
            preserve_default=False,
        ),
    ]
