# Generated by Django 5.0.7 on 2024-07-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_shoplisting_is_valid_adslisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslisting',
            name='ad_image',
            field=models.ImageField(upload_to='static/assets/ads_images'),
        ),
        migrations.AlterField(
            model_name='adslisting',
            name='contact_email',
            field=models.CharField(max_length=255),
        ),
    ]
