# Generated by Django 5.0.7 on 2024-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_adslisting_ad_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=100)),
                ('blog_img', models.ImageField(upload_to='static/assets/article_imgs')),
                ('para_one', models.CharField(max_length=1000)),
                ('para_two', models.CharField(max_length=1000)),
                ('para_trhee', models.CharField(max_length=1000)),
                ('para_four', models.CharField(max_length=1000)),
                ('para_five', models.CharField(max_length=1000)),
            ],
        ),
    ]
