# Generated by Django 5.0.7 on 2024-07-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_articlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articlemodel')),
            ],
        ),
    ]
