# Generated by Django 5.0.7 on 2024-08-03 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_likedshops'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_star', models.CharField(max_length=5)),
                ('user_review', models.CharField(max_length=2000)),
                ('shop_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shoplisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
