# Generated by Django 5.0.7 on 2024-08-03 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shopreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreview',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
